### ISSUE TITLE
Curious why you need to sns queues for the master

### ISSUE THREAD

**Issue by eedgar** [wcannon/saltconf2015#5]
William,
I was wondering what the design decision was to have two sns queues for the masters when you went to the multimaster design?  What problem does that solve?  Does that mean you would need a new queue if you wanted 3 masters?

Thanks in advance,
Eric

**Comment by wcannon** [comment]
Eric,

I'm impressed that you checked out my presentation from SaltConf.

The latest/final version of phoenix used sns topics paired with sqs
queues.  One pair (sns + queue) was used for autoscaling events for ec2
instances that are "masters".  The second pair was used for autoscaling
events for ec2 instances that are "'minions".

By having separate queues for master versus minion related autoscaling
events I can easily make other things happen - e.g. populate info into a
"masters" dynamodb table or a "minions" dynamodb table.

In answer to your question, no.  I need a min and max of two sns/sqs pairs
per aws region (one for minions, one for masters).

I just realized this might sound a little strange b/c the presentation
covered using dns for finding masters.  The final version of phoenix
removed the need for dns to find masters by having minions update their
list of masters by querying dynamodb directly (small python script).

Hope this helps clear things up.
ttys,
William

**Comment by wcannon** [comment]
One side note:  you might wonder why I chose to use sqs at all.  The goal
of the project was to make a highly available system where any or all
systems would essentially be able to replace themselves.

Sns is instantaneous.  If a notification is missed it cannot be retrieved
later.  Also, I considered using the salt master web hooks to receive sns
notifications.  They could not be walled off completely from internet
traffic.

Sqs however, fits this model well.  Imagine the scenario where all salt
masters are terminated due to multiple hardware issues.  When new salt
masters are launched automatically by aws autoscaling they configure
themselves and begin "working."  One of the jobs they do is pull messages
from sqs queues and update dynamodb tables.  Using sqs queues we will
ensure not to miss autoscaling events, even for the masters themselves!

I'm sure this is more than you wanted to know.

ttys
